/**
 * Mapping of French department IDs (1-95) to their names
 * Used for constructing URLs to filter auctions by department
 */
export const DEPARTMENT_NAMES_MAP: Record<number, string> = {
  1: 'ain',
  2: 'aisne',
  3: 'allier',
  4: 'alpes-de-haute-provence',
  5: 'hautes-alpes',
  6: 'alpes-maritimes',
  7: 'ardeche',
  8: 'ardennes',
  9: 'ariege',
  10: 'aube',
  11: 'aude',
  12: 'aveyron',
  13: 'bouches-du-rhone',
  14: 'calvados',
  15: 'cantal',
  16: 'charente',
  17: 'charente-maritime',
  18: 'cher',
  19: 'correze',
  21: 'cote-d-or',
  22: 'cotes-d-armor',
  23: 'creuse',
  24: 'dordogne',
  25: 'doubs',
  26: 'drome',
  27: 'eure',
  28: 'eure-et-loir',
  29: 'finistere',
  30: 'gard',
  31: 'haute-garonne',
  32: 'gers',
  33: 'gironde',
  34: 'herault',
  35: 'ille-et-vilaine',
  36: 'indre',
  37: 'indre-et-loire',
  38: 'isere',
  39: 'jura',
  40: 'landes',
  41: 'loir-et-cher',
  42: 'loire',
  43: 'haute-loire',
  44: 'loire-atlantique',
  45: 'loiret',
  46: 'lot',
  47: 'lot-et-garonne',
  48: 'lozere',
  49: 'maine-et-loire',
  50: 'manche',
  51: 'marne',
  52: 'haute-marne',
  53: 'mayenne',
  54: 'meurthe-et-moselle',
  55: 'meuse',
  56: 'morbihan',
  57: 'moselle',
  58: 'nievre',
  59: 'nord',
  60: 'oise',
  61: 'orne',
  62: 'pas-de-calais',
  63: 'puy-de-dome',
  64: 'pyrenees-atlantiques',
  65: 'hautes-pyrenees',
  66: 'pyrenees-orientales',
  67: 'bas-rhin',
  68: 'haut-rhin',
  69: 'rhone',
  70: 'haute-saone',
  71: 'saone-et-loire',
  72: 'sarthe',
  73: 'savoie',
  74: 'haute-savoie',
  75: 'paris',
  76: 'seine-maritime',
  77: 'seine-et-marne',
  78: 'yvelines',
  79: 'deux-sevres',
  80: 'somme',
  81: 'tarn',
  82: 'tarn-et-garonne',
  83: 'var',
  84: 'vaucluse',
  85: 'vendee',
  86: 'vienne',
  87: 'haute-vienne',
  88: 'vosges',
  89: 'yonne',
  90: 'territoire-de-belfort',
  91: 'essonne',
  92: 'hauts-de-seine',
  93: 'seine-saint-denis',
  94: 'val-de-marne',
  95: 'val-d-oise',
  // Note: 20 (Corse) was split into 2A and 2B in 1976
  // These are typically not included in 1-95 range
};

export const DEPARTMENT_IDS_MAP: Record<string, number> = Object.fromEntries(
  Object.entries(DEPARTMENT_NAMES_MAP).map(([key, value]) => [
    value,
    Number(key),
  ])
);
