export const SCRAPING_QUEUE: string = 'SCRAPING';
export const SOURCE_COMPANY_BUILDINGS_QUEUE: string =
  'SOURCE_COMPANY_BUILDINGS';
export const INGEST_DECEASES_CSV_QUEUE: string = 'INGEST_DECEASES_CSV';
export const SOURCE_ENERGY_SIEVES_QUEUE: string = 'SOURCE_ENERGY_SIEVES';
export const SOURCE_FAILING_COMPANIES_REQUESTED_QUEUE: string =
  'SOURCE_FAILING_COMPANIES_REQUESTED';
export const SOURCE_LISTINGS_QUEUE: string = 'SOURCE_LISTINGS';
