export const SCRAPING_QUEUE: string = 'SCRAPING';
export const SOURCE_COMPANY_BUILDINGS_QUEUE: string = 'SOURCE_COMPANY_BUILDINGS';
export const SOURCE_DECEASES_QUEUE: string = 'SOURCE_DECEASES';
export const SOURCE_DECEASES_CSV_INGEST_QUEUE: string = 'SOURCE_DECEASES_CSV_INGEST';
export const SOURCE_DECEASES_CSV_PROCESS_QUEUE: string = 'SOURCE_DECEASES_CSV_PROCESS';
export const SOURCE_ENERGY_SIEVES_QUEUE: string = 'SOURCE_ENERGY_SIEVES';
export const SOURCE_FAILING_COMPANIES_REQUESTED_QUEUE: string =
  'SOURCE_FAILING_COMPANIES_REQUESTED';
